# Autogenerated wrapper script for PlutoBook_jll for armv6l-linux-gnueabihf-cxx03
export html2pdf, html2png, libplutobook

using Cairo_jll
using FreeType2_jll
using Fontconfig_jll
using HarfBuzz_jll
using Expat_jll
using ICU_jll
using LibCURL_jll
using JpegTurbo_jll
using libwebp_jll
JLLWrappers.@generate_wrapper_header("PlutoBook")
JLLWrappers.@declare_library_product(libplutobook, "libplutobook.so.0")
JLLWrappers.@declare_executable_product(html2pdf)
JLLWrappers.@declare_executable_product(html2png)
function __init__()
    JLLWrappers.@generate_init_header(Cairo_jll, FreeType2_jll, Fontconfig_jll, HarfBuzz_jll, Expat_jll, ICU_jll, LibCURL_jll, JpegTurbo_jll, libwebp_jll)
    JLLWrappers.@init_library_product(
        libplutobook,
        "lib/libplutobook.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        html2pdf,
        "bin/html2pdf",
    )

    JLLWrappers.@init_executable_product(
        html2png,
        "bin/html2png",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
